###한림대학교 소프트웨어 융합 대학 특강

##누구나 즐기는 딥러닝: 오픈소스 Keras를 활용하여!!!

이정근 교수

빅데이터전공주임/오픈소스소프트웨어센터장 소프트웨어융합대학

jeonggun.lee@hallym.ac.kr 2019년 5월


---


###Keras 딥러닝: AND 논리 함수


In [0]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(1, input_dim=2))


In [0]:
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

Epoch 1/1000
4/4 [==============================] - 0s 29ms/step - loss: 0.2355
Epoch 2/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2344
Epoch 3/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2337
Epoch 4/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2323
Epoch 5/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2312
Epoch 6/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2307
Epoch 7/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2295
Epoch 8/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2287
Epoch 9/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2278
Epoch 10/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2270
Epoch 11/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2264
Epoch 12/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2252
Epoch 13/1000
4/4 [=============================

In [0]:
model.predict(data)

array([[-0.19979435],
       [ 0.25449848],
       [ 0.26255825],
       [ 0.71685106]], dtype=float32)

## Sigmoid 활성 함수 사용

좀더 성능을 끌어올릴 수 있는 방법으로 활성화 함수를 사용해보겠습니다.

AND 함수의 경우 출력이 0 또는 1에 해당하기 때문에, **sigmoid** 함수를 사용하도록 하겠습니다.


---



---



In [4]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

model.predict(data)

Epoch 1/1000
4/4 [==============================] - 0s 35ms/step - loss: 0.2896
Epoch 2/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2887
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2880
Epoch 4/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2875
Epoch 5/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2867
Epoch 6/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2861
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2856
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2848
Epoch 9/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2843
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2836
Epoch 11/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2827
Epoch 12/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2823
Epoch 13/1000
4/4 [=============================

array([[0.190389  ],
       [0.39711803],
       [0.29115155],
       [0.5349924 ]], dtype=float32)

## 성능 향상을 위한 다층 신경망 구성

층의 수를 좀더 늘려볼까요 ?


---



---



In [6]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

model.predict(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


Epoch 1/1000
4/4 [==============================] - 0s 55ms/step - loss: 0.2495
Epoch 2/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2491
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2488
Epoch 4/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2483
Epoch 5/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2482
Epoch 6/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2477
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2474
Epoch 8/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.2470
Epoch 9/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2468
Epoch 10/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2465
Epoch 11/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2460
Epoch 12/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2457
Epoch 13/1000
4/4 [=============================

array([[0.01443544],
       [0.08588159],
       [0.0616675 ],
       [0.90130985]], dtype=float32)

## 성능 향상을 위한 깊은 (?) 신경망 구성

층의 수를 하나 더 늘려 볼까요 ?


---



---



In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np 

data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outcome = np.array([[0], [0], [0], [1]])

model = Sequential()
model.add(Dense(8, input_dim=2, activation='relu'))
model.add(Dense(4, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(data, outcome, epochs=1000, batch_size=1)

model.predict(data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(4, activation="relu", kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()


Epoch 1/1000
4/4 [==============================] - 0s 67ms/step - loss: 0.2500
Epoch 2/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2496
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2494
Epoch 4/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2489
Epoch 5/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2486
Epoch 6/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2485
Epoch 7/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2480
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2477
Epoch 9/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2473
Epoch 10/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2469
Epoch 11/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2468
Epoch 12/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.2464
Epoch 13/1000
4/4 [=============================

array([[0.00455073],
       [0.01565436],
       [0.0066838 ],
       [0.975691  ]], dtype=float32)